/*
 * Abella
 * Partner API application
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.prompto.sdk.api;

import io.prompto.sdk.api.ApiException;
import io.prompto.sdk.model.InvoiceListResponse;
import io.prompto.sdk.model.InvoiceResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for InvoiceUiResourceApi
 */
@Ignore
public class InvoiceUiResourceApiTest {

    private final InvoiceUiResourceApi api = new InvoiceUiResourceApi("", "", "");

    
    /**
     * get
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getUsingGETTest() throws ApiException {
        String invoiceId = null;
        InvoiceResponse response = api.getUsingGET(invoiceId);

        // TODO: test validations
    }
    
    /**
     * list
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listUsingGETTest() throws ApiException {
        Integer limit = null;
        Integer offset = null;
        String q = null;
        InvoiceListResponse response = api.listUsingGET(limit, offset, q);

        // TODO: test validations
    }
    
}
