/*
 * Abella
 * Partner API application
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.prompto.sdk.api;

import io.prompto.sdk.api.ApiException;
import io.prompto.sdk.model.ByteArrayResource;
import io.prompto.sdk.model.ClearInvoiceRequest;
import io.prompto.sdk.model.CreateInvoiceRequest;
import java.io.File;
import io.prompto.sdk.model.InvoiceClearedResponse;
import io.prompto.sdk.model.InvoiceListResponse;
import io.prompto.sdk.model.InvoiceResponse;
import io.prompto.sdk.model.RestResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for InvoiceUiResourceApi
 */
@Ignore
public class InvoiceUiResourceApiTest {

    private final InvoiceUiResourceApi api = new InvoiceUiResourceApi("", "", "");

    
    /**
     * attachFile
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void attachFileUsingPOSTTest() throws ApiException {
        String invoiceId = null;
        File file = null;
        RestResponse response = api.attachFileUsingPOST(invoiceId, file);

        // TODO: test validations
    }
    
    /**
     * cancelInvoice
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void cancelInvoiceUsingPOSTTest() throws ApiException {
        String invoiceId = null;
        RestResponse response = api.cancelInvoiceUsingPOST(invoiceId);

        // TODO: test validations
    }
    
    /**
     * clearInvoice
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void clearInvoiceUsingPOSTTest() throws ApiException {
        String invoiceId = null;
        ClearInvoiceRequest req = null;
        InvoiceClearedResponse response = api.clearInvoiceUsingPOST(invoiceId, req);

        // TODO: test validations
    }
    
    /**
     * createInvoice
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createInvoiceUsingPOSTTest() throws ApiException {
        CreateInvoiceRequest req = null;
        InvoiceResponse response = api.createInvoiceUsingPOST(req);

        // TODO: test validations
    }
    
    /**
     * download
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void downloadUsingGETTest() throws ApiException {
        String invoiceId = null;
        ByteArrayResource response = api.downloadUsingGET(invoiceId);

        // TODO: test validations
    }
    
    /**
     * getDetail
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getDetailUsingGETTest() throws ApiException {
        String invoiceId = null;
        InvoiceResponse response = api.getDetailUsingGET(invoiceId);

        // TODO: test validations
    }
    
    /**
     * list
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listUsingGET3Test() throws ApiException {
        Integer limit = null;
        Integer offset = null;
        String q = null;
        InvoiceListResponse response = api.listUsingGET3(limit, offset, q);

        // TODO: test validations
    }
    
}
