/*
 * Abella
 * Partner API application
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.prompto.sdk.api;

import io.prompto.sdk.api.ApiException;
import io.prompto.sdk.model.PlanListResponse;
import io.prompto.sdk.model.PlanRequest;
import io.prompto.sdk.model.PlanResponse;
import io.prompto.sdk.model.RestResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PlanUiResourceApi
 */
@Ignore
public class PlanUiResourceApiTest {

    private final PlanUiResourceApi api = new PlanUiResourceApi("", "", "");

    
    /**
     * delete
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteUsingPOST1Test() throws ApiException {
        String planId = null;
        RestResponse response = api.deleteUsingPOST1(planId);

        // TODO: test validations
    }
    
    /**
     * get
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getUsingGET2Test() throws ApiException {
        String planId = null;
        PlanResponse response = api.getUsingGET2(planId);

        // TODO: test validations
    }
    
    /**
     * list
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listUsingGET2Test() throws ApiException {
        Integer limit = null;
        Integer offset = null;
        String q = null;
        PlanListResponse response = api.listUsingGET2(limit, offset, q);

        // TODO: test validations
    }
    
    /**
     * publish
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void publishUsingPOSTTest() throws ApiException {
        String planId = null;
        PlanResponse response = api.publishUsingPOST(planId);

        // TODO: test validations
    }
    
    /**
     * save
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void saveUsingPOSTTest() throws ApiException {
        PlanRequest planReq = null;
        PlanResponse response = api.saveUsingPOST(planReq);

        // TODO: test validations
    }
    
    /**
     * unpublish
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void unpublishUsingPOSTTest() throws ApiException {
        String planId = null;
        PlanResponse response = api.unpublishUsingPOST(planId);

        // TODO: test validations
    }
    
    /**
     * update
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateUsingPOST1Test() throws ApiException {
        String planId = null;
        PlanRequest planReq = null;
        PlanResponse response = api.updateUsingPOST1(planId, planReq);

        // TODO: test validations
    }
    
}
