/*
 * Abella
 * Partner API application
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.prompto.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.prompto.sdk.model.PersonalLoan;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import java.io.Serializable;

/**
 * CreatePersonalLoanRequest
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-04-09T15:57:22.781-05:00")
public class CreatePersonalLoanRequest implements Serializable {
  private static final long serialVersionUID = 1L;

  @SerializedName("chargeInitialPayment")
  private Boolean chargeInitialPayment = null;

  @SerializedName("initialPayment")
  private BigDecimal initialPayment = null;

  /**
   * Gets or Sets initialPaymentMethodType
   */
  @JsonAdapter(InitialPaymentMethodTypeEnum.Adapter.class)
  public enum InitialPaymentMethodTypeEnum {
    CREDIT_CARD("CREDIT_CARD"),
    
    ACH("ACH"),
    
    POS("POS"),
    
    CASH("CASH"),
    
    CHECK("CHECK");

    private String value;

    InitialPaymentMethodTypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static InitialPaymentMethodTypeEnum fromValue(String text) {
      for (InitialPaymentMethodTypeEnum b : InitialPaymentMethodTypeEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<InitialPaymentMethodTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final InitialPaymentMethodTypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public InitialPaymentMethodTypeEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return InitialPaymentMethodTypeEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("initialPaymentMethodType")
  private InitialPaymentMethodTypeEnum initialPaymentMethodType = null;

  @SerializedName("loan")
  private PersonalLoan loan = null;

  @SerializedName("timestamp")
  private Long timestamp = null;

  public CreatePersonalLoanRequest chargeInitialPayment(Boolean chargeInitialPayment) {
    this.chargeInitialPayment = chargeInitialPayment;
    return this;
  }

   /**
   * Get chargeInitialPayment
   * @return chargeInitialPayment
  **/
  @ApiModelProperty(value = "")
  public Boolean isChargeInitialPayment() {
    return chargeInitialPayment;
  }

  public void setChargeInitialPayment(Boolean chargeInitialPayment) {
    this.chargeInitialPayment = chargeInitialPayment;
  }

  public CreatePersonalLoanRequest initialPayment(BigDecimal initialPayment) {
    this.initialPayment = initialPayment;
    return this;
  }

   /**
   * Get initialPayment
   * @return initialPayment
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getInitialPayment() {
    return initialPayment;
  }

  public void setInitialPayment(BigDecimal initialPayment) {
    this.initialPayment = initialPayment;
  }

  public CreatePersonalLoanRequest initialPaymentMethodType(InitialPaymentMethodTypeEnum initialPaymentMethodType) {
    this.initialPaymentMethodType = initialPaymentMethodType;
    return this;
  }

   /**
   * Get initialPaymentMethodType
   * @return initialPaymentMethodType
  **/
  @ApiModelProperty(value = "")
  public InitialPaymentMethodTypeEnum getInitialPaymentMethodType() {
    return initialPaymentMethodType;
  }

  public void setInitialPaymentMethodType(InitialPaymentMethodTypeEnum initialPaymentMethodType) {
    this.initialPaymentMethodType = initialPaymentMethodType;
  }

  public CreatePersonalLoanRequest loan(PersonalLoan loan) {
    this.loan = loan;
    return this;
  }

   /**
   * Get loan
   * @return loan
  **/
  @ApiModelProperty(value = "")
  public PersonalLoan getLoan() {
    return loan;
  }

  public void setLoan(PersonalLoan loan) {
    this.loan = loan;
  }

  public CreatePersonalLoanRequest timestamp(Long timestamp) {
    this.timestamp = timestamp;
    return this;
  }

   /**
   * Get timestamp
   * @return timestamp
  **/
  @ApiModelProperty(value = "")
  public Long getTimestamp() {
    return timestamp;
  }

  public void setTimestamp(Long timestamp) {
    this.timestamp = timestamp;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreatePersonalLoanRequest createPersonalLoanRequest = (CreatePersonalLoanRequest) o;
    return Objects.equals(this.chargeInitialPayment, createPersonalLoanRequest.chargeInitialPayment) &&
        Objects.equals(this.initialPayment, createPersonalLoanRequest.initialPayment) &&
        Objects.equals(this.initialPaymentMethodType, createPersonalLoanRequest.initialPaymentMethodType) &&
        Objects.equals(this.loan, createPersonalLoanRequest.loan) &&
        Objects.equals(this.timestamp, createPersonalLoanRequest.timestamp);
  }

  @Override
  public int hashCode() {
    return Objects.hash(chargeInitialPayment, initialPayment, initialPaymentMethodType, loan, timestamp);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreatePersonalLoanRequest {\n");
    
    sb.append("    chargeInitialPayment: ").append(toIndentedString(chargeInitialPayment)).append("\n");
    sb.append("    initialPayment: ").append(toIndentedString(initialPayment)).append("\n");
    sb.append("    initialPaymentMethodType: ").append(toIndentedString(initialPaymentMethodType)).append("\n");
    sb.append("    loan: ").append(toIndentedString(loan)).append("\n");
    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

