/*
 * Abella
 * Partner API application
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.prompto.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.prompto.sdk.model.Invoice;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.io.Serializable;

/**
 * CreateInvoiceRequest
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-04-09T15:57:22.781-05:00")
public class CreateInvoiceRequest implements Serializable {
  private static final long serialVersionUID = 1L;

  @SerializedName("invoice")
  private Invoice invoice = null;

  @SerializedName("lastName1")
  private String lastName1 = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("organization")
  private String organization = null;

  @SerializedName("phoneExtNumber")
  private String phoneExtNumber = null;

  @SerializedName("phoneNumber")
  private String phoneNumber = null;

  /**
   * Gets or Sets prefix
   */
  @JsonAdapter(PrefixEnum.Adapter.class)
  public enum PrefixEnum {
    MR("MR"),
    
    MRS("MRS"),
    
    MS("MS"),
    
    MISS("MISS");

    private String value;

    PrefixEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static PrefixEnum fromValue(String text) {
      for (PrefixEnum b : PrefixEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<PrefixEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final PrefixEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public PrefixEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return PrefixEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("prefix")
  private PrefixEnum prefix = null;

  @SerializedName("taxNumber")
  private String taxNumber = null;

  @SerializedName("timestamp")
  private Long timestamp = null;

  @SerializedName("username")
  private String username = null;

  public CreateInvoiceRequest invoice(Invoice invoice) {
    this.invoice = invoice;
    return this;
  }

   /**
   * Get invoice
   * @return invoice
  **/
  @ApiModelProperty(value = "")
  public Invoice getInvoice() {
    return invoice;
  }

  public void setInvoice(Invoice invoice) {
    this.invoice = invoice;
  }

  public CreateInvoiceRequest lastName1(String lastName1) {
    this.lastName1 = lastName1;
    return this;
  }

   /**
   * Get lastName1
   * @return lastName1
  **/
  @ApiModelProperty(value = "")
  public String getLastName1() {
    return lastName1;
  }

  public void setLastName1(String lastName1) {
    this.lastName1 = lastName1;
  }

  public CreateInvoiceRequest name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public CreateInvoiceRequest organization(String organization) {
    this.organization = organization;
    return this;
  }

   /**
   * Get organization
   * @return organization
  **/
  @ApiModelProperty(value = "")
  public String getOrganization() {
    return organization;
  }

  public void setOrganization(String organization) {
    this.organization = organization;
  }

  public CreateInvoiceRequest phoneExtNumber(String phoneExtNumber) {
    this.phoneExtNumber = phoneExtNumber;
    return this;
  }

   /**
   * Get phoneExtNumber
   * @return phoneExtNumber
  **/
  @ApiModelProperty(value = "")
  public String getPhoneExtNumber() {
    return phoneExtNumber;
  }

  public void setPhoneExtNumber(String phoneExtNumber) {
    this.phoneExtNumber = phoneExtNumber;
  }

  public CreateInvoiceRequest phoneNumber(String phoneNumber) {
    this.phoneNumber = phoneNumber;
    return this;
  }

   /**
   * Get phoneNumber
   * @return phoneNumber
  **/
  @ApiModelProperty(value = "")
  public String getPhoneNumber() {
    return phoneNumber;
  }

  public void setPhoneNumber(String phoneNumber) {
    this.phoneNumber = phoneNumber;
  }

  public CreateInvoiceRequest prefix(PrefixEnum prefix) {
    this.prefix = prefix;
    return this;
  }

   /**
   * Get prefix
   * @return prefix
  **/
  @ApiModelProperty(value = "")
  public PrefixEnum getPrefix() {
    return prefix;
  }

  public void setPrefix(PrefixEnum prefix) {
    this.prefix = prefix;
  }

  public CreateInvoiceRequest taxNumber(String taxNumber) {
    this.taxNumber = taxNumber;
    return this;
  }

   /**
   * Get taxNumber
   * @return taxNumber
  **/
  @ApiModelProperty(value = "")
  public String getTaxNumber() {
    return taxNumber;
  }

  public void setTaxNumber(String taxNumber) {
    this.taxNumber = taxNumber;
  }

  public CreateInvoiceRequest timestamp(Long timestamp) {
    this.timestamp = timestamp;
    return this;
  }

   /**
   * Get timestamp
   * @return timestamp
  **/
  @ApiModelProperty(value = "")
  public Long getTimestamp() {
    return timestamp;
  }

  public void setTimestamp(Long timestamp) {
    this.timestamp = timestamp;
  }

  public CreateInvoiceRequest username(String username) {
    this.username = username;
    return this;
  }

   /**
   * Get username
   * @return username
  **/
  @ApiModelProperty(value = "")
  public String getUsername() {
    return username;
  }

  public void setUsername(String username) {
    this.username = username;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateInvoiceRequest createInvoiceRequest = (CreateInvoiceRequest) o;
    return Objects.equals(this.invoice, createInvoiceRequest.invoice) &&
        Objects.equals(this.lastName1, createInvoiceRequest.lastName1) &&
        Objects.equals(this.name, createInvoiceRequest.name) &&
        Objects.equals(this.organization, createInvoiceRequest.organization) &&
        Objects.equals(this.phoneExtNumber, createInvoiceRequest.phoneExtNumber) &&
        Objects.equals(this.phoneNumber, createInvoiceRequest.phoneNumber) &&
        Objects.equals(this.prefix, createInvoiceRequest.prefix) &&
        Objects.equals(this.taxNumber, createInvoiceRequest.taxNumber) &&
        Objects.equals(this.timestamp, createInvoiceRequest.timestamp) &&
        Objects.equals(this.username, createInvoiceRequest.username);
  }

  @Override
  public int hashCode() {
    return Objects.hash(invoice, lastName1, name, organization, phoneExtNumber, phoneNumber, prefix, taxNumber, timestamp, username);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateInvoiceRequest {\n");
    
    sb.append("    invoice: ").append(toIndentedString(invoice)).append("\n");
    sb.append("    lastName1: ").append(toIndentedString(lastName1)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    organization: ").append(toIndentedString(organization)).append("\n");
    sb.append("    phoneExtNumber: ").append(toIndentedString(phoneExtNumber)).append("\n");
    sb.append("    phoneNumber: ").append(toIndentedString(phoneNumber)).append("\n");
    sb.append("    prefix: ").append(toIndentedString(prefix)).append("\n");
    sb.append("    taxNumber: ").append(toIndentedString(taxNumber)).append("\n");
    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("    username: ").append(toIndentedString(username)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

