/*
 * Abella
 * Partner API application
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.prompto.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.prompto.sdk.model.Address;
import io.prompto.sdk.model.Link;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.io.Serializable;

/**
 * CustomerUser
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-03-30T14:10:18.057-06:00")
public class CustomerUser implements Serializable {
  private static final long serialVersionUID = 1L;

  @SerializedName("_id")
  private String id = null;

  @SerializedName("address")
  private Address address = null;

  @SerializedName("birthDate")
  private Long birthDate = null;

  @SerializedName("blocked")
  private Boolean blocked = null;

  @SerializedName("createDate")
  private Long createDate = null;

  @SerializedName("fullName")
  private String fullName = null;

  @SerializedName("lastName1")
  private String lastName1 = null;

  @SerializedName("lastName2")
  private String lastName2 = null;

  @SerializedName("links")
  private List<Link> links = null;

  @SerializedName("middleName")
  private String middleName = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("organization")
  private String organization = null;

  @SerializedName("partnerId")
  private String partnerId = null;

  @SerializedName("phoneExtNumber1")
  private String phoneExtNumber1 = null;

  @SerializedName("phoneExtNumber2")
  private String phoneExtNumber2 = null;

  @SerializedName("phoneNumber1")
  private String phoneNumber1 = null;

  @SerializedName("phoneNumber2")
  private String phoneNumber2 = null;

  @SerializedName("pictureFilename")
  private String pictureFilename = null;

  /**
   * Gets or Sets prefix
   */
  @JsonAdapter(PrefixEnum.Adapter.class)
  public enum PrefixEnum {
    MR("MR"),
    
    MRS("MRS"),
    
    MS("MS"),
    
    MISS("MISS");

    private String value;

    PrefixEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static PrefixEnum fromValue(String text) {
      for (PrefixEnum b : PrefixEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<PrefixEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final PrefixEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public PrefixEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return PrefixEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("prefix")
  private PrefixEnum prefix = null;

  /**
   * Gets or Sets status
   */
  @JsonAdapter(StatusEnum.Adapter.class)
  public enum StatusEnum {
    ACTIVE("ACTIVE"),
    
    DISABLED("DISABLED"),
    
    PENDING_ACTIVATION("PENDING_ACTIVATION");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static StatusEnum fromValue(String text) {
      for (StatusEnum b : StatusEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<StatusEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final StatusEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public StatusEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return StatusEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("status")
  private StatusEnum status = null;

  @SerializedName("taxNumber")
  private String taxNumber = null;

  @SerializedName("username")
  private String username = null;

  public CustomerUser id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public CustomerUser address(Address address) {
    this.address = address;
    return this;
  }

   /**
   * Get address
   * @return address
  **/
  @ApiModelProperty(value = "")
  public Address getAddress() {
    return address;
  }

  public void setAddress(Address address) {
    this.address = address;
  }

  public CustomerUser birthDate(Long birthDate) {
    this.birthDate = birthDate;
    return this;
  }

   /**
   * Get birthDate
   * @return birthDate
  **/
  @ApiModelProperty(value = "")
  public Long getBirthDate() {
    return birthDate;
  }

  public void setBirthDate(Long birthDate) {
    this.birthDate = birthDate;
  }

  public CustomerUser blocked(Boolean blocked) {
    this.blocked = blocked;
    return this;
  }

   /**
   * Get blocked
   * @return blocked
  **/
  @ApiModelProperty(value = "")
  public Boolean isBlocked() {
    return blocked;
  }

  public void setBlocked(Boolean blocked) {
    this.blocked = blocked;
  }

  public CustomerUser createDate(Long createDate) {
    this.createDate = createDate;
    return this;
  }

   /**
   * Get createDate
   * @return createDate
  **/
  @ApiModelProperty(value = "")
  public Long getCreateDate() {
    return createDate;
  }

  public void setCreateDate(Long createDate) {
    this.createDate = createDate;
  }

  public CustomerUser fullName(String fullName) {
    this.fullName = fullName;
    return this;
  }

   /**
   * Get fullName
   * @return fullName
  **/
  @ApiModelProperty(value = "")
  public String getFullName() {
    return fullName;
  }

  public void setFullName(String fullName) {
    this.fullName = fullName;
  }

  public CustomerUser lastName1(String lastName1) {
    this.lastName1 = lastName1;
    return this;
  }

   /**
   * Get lastName1
   * @return lastName1
  **/
  @ApiModelProperty(value = "")
  public String getLastName1() {
    return lastName1;
  }

  public void setLastName1(String lastName1) {
    this.lastName1 = lastName1;
  }

  public CustomerUser lastName2(String lastName2) {
    this.lastName2 = lastName2;
    return this;
  }

   /**
   * Get lastName2
   * @return lastName2
  **/
  @ApiModelProperty(value = "")
  public String getLastName2() {
    return lastName2;
  }

  public void setLastName2(String lastName2) {
    this.lastName2 = lastName2;
  }

  public CustomerUser links(List<Link> links) {
    this.links = links;
    return this;
  }

  public CustomerUser addLinksItem(Link linksItem) {
    if (this.links == null) {
      this.links = new ArrayList<Link>();
    }
    this.links.add(linksItem);
    return this;
  }

   /**
   * Get links
   * @return links
  **/
  @ApiModelProperty(value = "")
  public List<Link> getLinks() {
    return links;
  }

  public void setLinks(List<Link> links) {
    this.links = links;
  }

  public CustomerUser middleName(String middleName) {
    this.middleName = middleName;
    return this;
  }

   /**
   * Get middleName
   * @return middleName
  **/
  @ApiModelProperty(value = "")
  public String getMiddleName() {
    return middleName;
  }

  public void setMiddleName(String middleName) {
    this.middleName = middleName;
  }

  public CustomerUser name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public CustomerUser organization(String organization) {
    this.organization = organization;
    return this;
  }

   /**
   * Get organization
   * @return organization
  **/
  @ApiModelProperty(value = "")
  public String getOrganization() {
    return organization;
  }

  public void setOrganization(String organization) {
    this.organization = organization;
  }

  public CustomerUser partnerId(String partnerId) {
    this.partnerId = partnerId;
    return this;
  }

   /**
   * Get partnerId
   * @return partnerId
  **/
  @ApiModelProperty(value = "")
  public String getPartnerId() {
    return partnerId;
  }

  public void setPartnerId(String partnerId) {
    this.partnerId = partnerId;
  }

  public CustomerUser phoneExtNumber1(String phoneExtNumber1) {
    this.phoneExtNumber1 = phoneExtNumber1;
    return this;
  }

   /**
   * Get phoneExtNumber1
   * @return phoneExtNumber1
  **/
  @ApiModelProperty(value = "")
  public String getPhoneExtNumber1() {
    return phoneExtNumber1;
  }

  public void setPhoneExtNumber1(String phoneExtNumber1) {
    this.phoneExtNumber1 = phoneExtNumber1;
  }

  public CustomerUser phoneExtNumber2(String phoneExtNumber2) {
    this.phoneExtNumber2 = phoneExtNumber2;
    return this;
  }

   /**
   * Get phoneExtNumber2
   * @return phoneExtNumber2
  **/
  @ApiModelProperty(value = "")
  public String getPhoneExtNumber2() {
    return phoneExtNumber2;
  }

  public void setPhoneExtNumber2(String phoneExtNumber2) {
    this.phoneExtNumber2 = phoneExtNumber2;
  }

  public CustomerUser phoneNumber1(String phoneNumber1) {
    this.phoneNumber1 = phoneNumber1;
    return this;
  }

   /**
   * Get phoneNumber1
   * @return phoneNumber1
  **/
  @ApiModelProperty(value = "")
  public String getPhoneNumber1() {
    return phoneNumber1;
  }

  public void setPhoneNumber1(String phoneNumber1) {
    this.phoneNumber1 = phoneNumber1;
  }

  public CustomerUser phoneNumber2(String phoneNumber2) {
    this.phoneNumber2 = phoneNumber2;
    return this;
  }

   /**
   * Get phoneNumber2
   * @return phoneNumber2
  **/
  @ApiModelProperty(value = "")
  public String getPhoneNumber2() {
    return phoneNumber2;
  }

  public void setPhoneNumber2(String phoneNumber2) {
    this.phoneNumber2 = phoneNumber2;
  }

  public CustomerUser pictureFilename(String pictureFilename) {
    this.pictureFilename = pictureFilename;
    return this;
  }

   /**
   * Get pictureFilename
   * @return pictureFilename
  **/
  @ApiModelProperty(value = "")
  public String getPictureFilename() {
    return pictureFilename;
  }

  public void setPictureFilename(String pictureFilename) {
    this.pictureFilename = pictureFilename;
  }

  public CustomerUser prefix(PrefixEnum prefix) {
    this.prefix = prefix;
    return this;
  }

   /**
   * Get prefix
   * @return prefix
  **/
  @ApiModelProperty(value = "")
  public PrefixEnum getPrefix() {
    return prefix;
  }

  public void setPrefix(PrefixEnum prefix) {
    this.prefix = prefix;
  }

  public CustomerUser status(StatusEnum status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(value = "")
  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(StatusEnum status) {
    this.status = status;
  }

  public CustomerUser taxNumber(String taxNumber) {
    this.taxNumber = taxNumber;
    return this;
  }

   /**
   * Get taxNumber
   * @return taxNumber
  **/
  @ApiModelProperty(value = "")
  public String getTaxNumber() {
    return taxNumber;
  }

  public void setTaxNumber(String taxNumber) {
    this.taxNumber = taxNumber;
  }

  public CustomerUser username(String username) {
    this.username = username;
    return this;
  }

   /**
   * Get username
   * @return username
  **/
  @ApiModelProperty(value = "")
  public String getUsername() {
    return username;
  }

  public void setUsername(String username) {
    this.username = username;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CustomerUser customerUser = (CustomerUser) o;
    return Objects.equals(this.id, customerUser.id) &&
        Objects.equals(this.address, customerUser.address) &&
        Objects.equals(this.birthDate, customerUser.birthDate) &&
        Objects.equals(this.blocked, customerUser.blocked) &&
        Objects.equals(this.createDate, customerUser.createDate) &&
        Objects.equals(this.fullName, customerUser.fullName) &&
        Objects.equals(this.lastName1, customerUser.lastName1) &&
        Objects.equals(this.lastName2, customerUser.lastName2) &&
        Objects.equals(this.links, customerUser.links) &&
        Objects.equals(this.middleName, customerUser.middleName) &&
        Objects.equals(this.name, customerUser.name) &&
        Objects.equals(this.organization, customerUser.organization) &&
        Objects.equals(this.partnerId, customerUser.partnerId) &&
        Objects.equals(this.phoneExtNumber1, customerUser.phoneExtNumber1) &&
        Objects.equals(this.phoneExtNumber2, customerUser.phoneExtNumber2) &&
        Objects.equals(this.phoneNumber1, customerUser.phoneNumber1) &&
        Objects.equals(this.phoneNumber2, customerUser.phoneNumber2) &&
        Objects.equals(this.pictureFilename, customerUser.pictureFilename) &&
        Objects.equals(this.prefix, customerUser.prefix) &&
        Objects.equals(this.status, customerUser.status) &&
        Objects.equals(this.taxNumber, customerUser.taxNumber) &&
        Objects.equals(this.username, customerUser.username);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, address, birthDate, blocked, createDate, fullName, lastName1, lastName2, links, middleName, name, organization, partnerId, phoneExtNumber1, phoneExtNumber2, phoneNumber1, phoneNumber2, pictureFilename, prefix, status, taxNumber, username);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CustomerUser {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    birthDate: ").append(toIndentedString(birthDate)).append("\n");
    sb.append("    blocked: ").append(toIndentedString(blocked)).append("\n");
    sb.append("    createDate: ").append(toIndentedString(createDate)).append("\n");
    sb.append("    fullName: ").append(toIndentedString(fullName)).append("\n");
    sb.append("    lastName1: ").append(toIndentedString(lastName1)).append("\n");
    sb.append("    lastName2: ").append(toIndentedString(lastName2)).append("\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("    middleName: ").append(toIndentedString(middleName)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    organization: ").append(toIndentedString(organization)).append("\n");
    sb.append("    partnerId: ").append(toIndentedString(partnerId)).append("\n");
    sb.append("    phoneExtNumber1: ").append(toIndentedString(phoneExtNumber1)).append("\n");
    sb.append("    phoneExtNumber2: ").append(toIndentedString(phoneExtNumber2)).append("\n");
    sb.append("    phoneNumber1: ").append(toIndentedString(phoneNumber1)).append("\n");
    sb.append("    phoneNumber2: ").append(toIndentedString(phoneNumber2)).append("\n");
    sb.append("    pictureFilename: ").append(toIndentedString(pictureFilename)).append("\n");
    sb.append("    prefix: ").append(toIndentedString(prefix)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    taxNumber: ").append(toIndentedString(taxNumber)).append("\n");
    sb.append("    username: ").append(toIndentedString(username)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

